steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/dashboard-studio', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/$PROJECT_ID/dashboard-studio']
images: ['us.gcr.io/$PROJECT_ID/dashboard-studio']